server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${username}
    password: ${dbpassword}
  data:
    redis:
      host: localhost
      port: 6379

  # JPA & Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # JWT 시크릿 키 (기존 설정)
  jwt:
    secret: 'OsvREsESUG7IErmzvcanI1CdfUP22M6mbwR/AZPURQ8='

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
